### ISSUE TITLE
hardware construction

### ISSUE THREAD

**Issue by ws786873** [934virginia/Norman#1]
I am very interested in this project. Have you completed the hardware construction and started testing?

**Comment by 934virginia** [comment]
I appreciate the interest! 
Unfortunately, I have no plans to create detailed guides or instructions for hardware configurations, as there are simply too many different approaches to cover. The library is complete and ready for deployment as controller software, and the practical example sketch along with the parameters file should be enough to get people started should they have an interest in using it. 
As for testing, you might want to check out my Plot.ly page linked in the readme. All of the dozen graphical comparisons between real climatic averages of various US cities and Norman's projections projections for those cities are there if you want to have a look.
I'm happy to consult or answer questions about build ideas you might have over email (934virginia@gmail.com), but I'm going to go ahead and close this issue in the meantime since I can't really address it in the code itself.
